server:
  port: 8087
  servlet:
    context-path: /web-clinic-application

api:
  nfz:
    url: https://api.nfz.gov.pl/app-umw-api/

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/web_clinic_app
    username: postgres
    password: password
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
      # do wyłaczenia
#  security:
#    enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  metrics:
    enable:
      http:
        server:
          requests: true
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true