server:
  port: 8087
  servlet:
    context-path: /web-clinic-application

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/web_clinic_app
    username: postgres
    password: password
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
      # do wyłaczenia
#  security:
#    enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG